# Generated by Django 4.2.11 on 2024-04-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_options_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin'},
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='full_name',
            new_name='name',
        ),
    ]
