# Generated by Django 4.2.11 on 2024-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_options_rename_full_name_worker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.CharField(choices=[('None', 'Не указано'), ('work-1', 'Не имеет значения'), ('work-2', 'Нет опыта'), ('work-3', 'От 1 года до 3 лет '), ('work-4', 'От 3 до 6 лет'), ('work-5', 'Более 6 лет')], default='None', max_length=20, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Критерии',
                'verbose_name_plural': 'Критерии',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
