# Generated by Django 4.2.11 on 2024-04-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_criteria_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('work_experience', models.CharField(choices=[('None', 'Не указано'), ('work-1', 'Не имеет значения'), ('work-2', 'Нет опыта'), ('work-3', 'От 1 года до 3 лет '), ('work-4', 'От 3 до 6 лет'), ('work-5', 'Более 6 лет')], default='None', max_length=20, verbose_name='Опыт работы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
