# Generated by Django 4.2.11 on 2024-04-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vacancy_delete_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категория вакансии')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категории вакансий',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_position',
            field=models.TextField(blank=True, verbose_name='Описание должности'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.vacancycategories'),
            preserve_default=False,
        ),
    ]
