# Generated by Django 4.2.11 on 2024-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_vacancy_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='type_employment',
            field=models.CharField(choices=[('None', 'Не указано'), ('employment-1', 'Полная занятость'), ('employment-2', 'Частичная занятость'), ('employment-3', 'Стажировка'), ('employment-4', 'Оформление по ГПХ или по совместительству')], default='None', max_length=50, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_experience',
            field=models.CharField(choices=[('None', 'Не указано'), ('work-1', 'Не имеет значения'), ('work-2', 'Нет опыта'), ('work-3', 'От 1 года до 3 лет'), ('work-4', 'От 3 до 6 лет'), ('work-5', 'Более 6 лет')], default='None', max_length=50, verbose_name='Опыт работы'),
        ),
    ]
