# Generated by Django 4.2.11 on 2024-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_vacancy_type_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('None', 'Не указано'), ('education-1', 'Не требуется или не указано'), ('education-2', 'Среднее профессиональное'), ('education-3', 'Высшее')], default='None', max_length=50, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=1, verbose_name='Заработная плата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule',
            field=models.CharField(choices=[('None', 'Не указано'), ('work-schedule-1', 'Полный день'), ('work-schedule-2', 'Вахтовый метод'), ('work-schedule-3', 'Сменный график'), ('work-schedule-4', 'Удаленная работа'), ('work-schedule-5', 'Гибкий график')], default='None', max_length=50, verbose_name='График работы'),
        ),
    ]
