# Generated by Django 4.2.11 on 2024-04-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_vacancy_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='created_at',
            new_name='created',
        ),
    ]
