# Generated by Django 4.2.11 on 2024-04-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_created_at_vacancy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
