# Generated by Django 4.2.11 on 2024-04-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_vacancy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('None', 'Не указано'), ('education-1', 'Не требуется или не указано'), ('education-2', 'Среднее профессиональное'), ('education-3', 'Высшее')], default='None', max_length=50, verbose_name='Образование'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.TextField(blank=True, verbose_name='Специализации')),
                ('salary', models.IntegerField(verbose_name='Заработная плата')),
                ('work_experience', models.CharField(choices=[('None', 'Не указано'), ('work-1', 'Не имеет значения'), ('work-2', 'Нет опыта'), ('work-3', 'От 1 года до 3 лет'), ('work-4', 'От 3 до 6 лет'), ('work-5', 'Более 6 лет')], default='None', max_length=50, verbose_name='Опыт работы')),
                ('type_employment', models.CharField(choices=[('None', 'Не указано'), ('employment-1', 'Полная занятость'), ('employment-2', 'Частичная занятость'), ('employment-3', 'Стажировка'), ('employment-4', 'Оформление по ГПХ или по совместительству')], default='None', max_length=50, verbose_name='Тип занятости')),
                ('work_schedule', models.CharField(choices=[('None', 'Не указано'), ('work-schedule-1', 'Полный день'), ('work-schedule-2', 'Вахтовый метод'), ('work-schedule-3', 'Сменный график'), ('work-schedule-4', 'Удаленная работа'), ('work-schedule-5', 'Гибкий график')], default='None', max_length=50, verbose_name='График работы')),
                ('education', models.CharField(choices=[('None', 'Не указано'), ('education-1', 'Не требуется или не указано'), ('education-2', 'Среднее профессиональное'), ('education-3', 'Высшее')], default='None', max_length=50, verbose_name='Образование')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
