# Generated by Django 4.2.11 on 2024-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_vacancy_education_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='file',
            field=models.FileField(blank=True, upload_to='files/resume/worker/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/users/workers/%Y/%m/%d/'),
        ),
    ]
