# Generated by Django 4.2.11 on 2024-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_vacancy_file_alter_user_phone_alter_worker_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='files/resume/worker/%Y/%m/%d/'),
        ),
    ]
