# Generated by Django 4.2.11 on 2024-04-09 08:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_vacancy_file_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path),
        ),
    ]
