# Generated by Django 4.2.11 on 2024-04-13 08:26

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to=main.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specializations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализации'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('None', 'Не указано'), ('Male', 'Мужчина'), ('Female', 'Женщина')], default='None', max_length=20, verbose_name='Пол'),
        ),
    ]
