# Generated by Django 5.0.2 on 2024-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_resume_file_alter_resume_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='specializations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализация'),
        ),
    ]
